mullvad/mullvadvpn-app-tests

- .gitignore
- BUILD_OS_IMAGE.md
- Cargo.lock
- README.md
- build.sh
- ci-runtests.sh
- runtests.sh
- scripts/setup-network.sh
- test-manager/Cargo.toml
- test-manager/src/config.rs
- test-manager/src/main.rs
- test-manager/src/network_monitor.rs
- test-manager/src/tests/mod.rs
- test-rpc/Cargo.toml
- test-rpc/src/lib.rs
- test-rpc/src/package.rs
- test-runner/Cargo.toml
- test-runner/src/main.rs
- test-runner/src/net.rs
- test-runner/src/package.rs
This PR includes a number of changes. Primarily the following:
* Set up networking without root access (using `rootlesskit`/`slirp4netns`).
* Add a "CI" script that takes as input any two Mullvad app versions (one version under test and one version to upgrade from) and 
* Clean up "config variables" in the test manager somewhat.
> Set up unprivileged networking using namespaces and add CI script

- test-manager/src/config.rs
- test-manager/src/logging.rs
- test-manager/src/tests/mod.rs
- test-rpc/src/lib.rs
- test-rpc/src/logging.rs
- test-rpc/src/mullvad_daemon.rs
- test-rpc/src/package.rs
- test-runner/Cargo.toml
- test-runner/src/app.rs
- test-runner/src/logging.rs
- test-runner/src/main.rs
- test-runner/src/net.rs
- test-runner/src/package.rs
Print log files and `settings.json` when a test fails.
Currently this always prints this on test failure, not sure if we want to be able to turn this on and off to avoid verbosity, but I imagine that tests failing is supposed to be a rarity and in that case you would want to see a bunch of data.
> Get log files output

- .gitignore
- ci-runtests-and-report.sh
- ci-runtests.sh
- runtests.sh
- scripts/build-runner-image.sh
- scripts/destroy-network.sh
- systemd/README.md
- systemd/mullvadvpn-app-tests.service
- systemd/mullvadvpn-app-tests.timer
- test-manager/src/main.rs
- test-runner/src/net.rs
- test-runner/src/package.rs
Includes a bunch of changes, but mainly:
* Test latest master against the version specified in `./dist-assets/desktop-product-version.txt` in the main app repo.
* Add a script for sending email reports after running the tests.
* Add a systemd timer example.
* Fix issue with `dnsmasq` not being killed.
* Switch from testing `TARGET`s to OSes, since the test runner image may be shared between different OS images.
* Return proper exit code from `test-manager`.
> Add scripts/service for running tests nightly and emailing the results

- test-rpc/src/transport.rs
- test-runner/src/main.rs
The server receives partial frames when the manager sends data too early, causing the server to restart and occasionally the test manager to fail.
> Ignore partial frames

- README.md
- ci-runtests.sh
- systemd/mullvadvpn-app-tests.service
Make it possible to specify multiple tokens. This is necessary for testing >5 OSes.
> Allow multiple account tokens to be specified with 'ACCOUNT_TOKENS'

- BUILD_OS_IMAGE.md
- Cargo.lock
- README.md
- ci-runtests.sh
- runtests.sh
- scripts/build-runner-image.sh
- systemd/mullvadvpn-app-tests.service
- test-manager/src/tests/helpers.rs
- test-rpc/src/package.rs
- test-rpc/src/transport.rs
- test-runner/Cargo.toml
- test-runner/src/net.rs
- test-runner/src/package.rs
Main changes:
* Ubuntu requires no changes. For Fedora, the package installer has just been updated to support DNF/RPMs.
* For Windows 11, as secure boot and a TPM are required, the scripts/instructions have been updated to include a TPM emulator and OVMF.
* Ignore any console output to the serial port during boot.
> Add Fedora, Ubuntu, and Windows 11 targets

- README.md
- test-runner/src/package.rs
The test runner sometimes starts before networking is available, causing DNF updates to fail. Disabling cache updates results in errors. Also, the test runner should not be dependent on networking. Since DNF returns no specific error code, we have to parse stderr and retry in case it fails due to a network error.
> Retry RPM package install

- Dockerfile
- README.md
- build.sh
- runtests.sh
- test-manager/src/tests/helpers.rs
- test-manager/src/tests/install.rs
- test-manager/src/tests/mod.rs
- test-manager/src/tests/tunnel.rs
- test-rpc/src/transport.rs
- test-runner/src/net.rs
- test-runner/src/package.rs
Changes:
* Fix the problem we have due to statically linking to glibc. We build in a container instead.
* Add retries to `am.i.mullvad.net` queries.
* Skip newlines (not CRLF) before receiving initial message/ping. This may still be brittle and the initial frame should possibly be replaced by a magic number/identifier.
* Wait for error state before upgrading instead of relying on timing.
> Build test runner in container

- ci-runtests-and-report.sh
Also strip non-printable characters, as they caused `mail` to interpret the logs as binary data.
> Send email attachment with filename

- ci-runtests.sh
The short one sometimes yields a 404.
> Use long commit hash for fetching product version from the app repo

- Cargo.lock
- test-manager/src/logging.rs
- test-manager/src/main.rs
- test-manager/src/tests/helpers.rs
- test-manager/src/tests/install.rs
- test-manager/src/tests/mod.rs
- test-manager/src/tests/tunnel.rs
- test-rpc/Cargo.toml
- test-rpc/src/client.rs
- test-rpc/src/lib.rs
- test-rpc/src/transport.rs
- test-runner/src/main.rs
- test-runner/src/net.rs
Partially so that the context does not have to be passed to the underlying client for each RPC. It is also required for implementing a reboot RPC.
> Add RPC client wrapper

- test-manager/src/tests/mod.rs
- test-manager/src/tests/tunnel.rs
Sanity checks the auto-connect setting. As is documented in the test, it is limited in that it does not test for leaks during shutdown or reboot.
> Add autoconnect tests

- ci-runtests.sh
- scripts/build-runner-image.sh
We cannot rely on the API  endpoint anymore since the last stable version differs between platforms. As a workaround for now, use the GitHub API to obtain the last release.
> Handle inconsistent desktop app versions

- test-manager/src/tests/helpers.rs
- test-manager/src/tests/tunnel.rs
- test-rpc/src/mullvad_daemon.rs
This fixes the flakiness seen in the auto-connect tests.
> Wait for Mullvad service after reboot

- Cargo.lock
- test-manager/Cargo.toml
- test-manager/src/tests/dns.rs
This PR adds tests for testing whether the system uses the correct resolver:
* `test_dns_config_default`
* `test_dns_config_custom_private`
* `test_dns_config_custom_public`
* `test_content_blockers`
These are separate from the [leak tests](https://github.com/mullvad/mullvadvpn-app-tests/pull/55).
> Test system DNS configuration

- Cargo.lock
- README.md
- scripts/destroy-network.sh
- scripts/setup-network.sh
- test-manager/Cargo.toml
- test-manager/src/config.rs
- test-manager/src/network_monitor.rs
- test-manager/src/tests/dns.rs
- test-manager/src/tests/helpers.rs
- test-manager/src/tests/install.rs
- test-manager/src/tests/mod.rs
- test-manager/src/tests/tunnel.rs
- test-rpc/src/client.rs
- test-rpc/src/lib.rs
- test-runner/src/main.rs
- test-runner/src/net.rs
These tests ensure that there are no DNS leaks, both inside and outside of the tunnel, for the default resolver and for custom DNS. They also make sure that outbound traffic *is* observed when expected.
In addition to leak tests, the PR also includes tests checking whether the system uses the correct resolver:
* `test_dns_config_default`
* `test_dns_config_custom_private`
* `test_dns_config_custom_public`
* `test_content_blockers`
Fixes DES-56.
Fixes DES-55.
> Add DNS configuration and leak tests

- test-manager/src/tests/account.rs
- test-manager/src/tests/install.rs
Kind of an ugly workaround, but since this error is very common, let's just add a long sleep followed by a retry.
Fixes DES-36.
> Retry some RPC calls if the cause is throttling

- Cargo.lock
- README.md
- scripts/ssh-setup.sh
- test-manager/Cargo.toml
- test-manager/build.rs
- test-manager/src/config.rs
- test-manager/src/main.rs
- test-manager/src/package.rs
- test-manager/src/run_tests.rs
- test-manager/src/vm/mod.rs
- test-manager/src/vm/provision.rs
- test-runner/src/main.rs
This makes it possible to set up test runners over SSH if the base image does not include the service. Meaning that we don't necessarily need to use custom built images.
This only works on macOS at the moment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/64)
> Add SSH provisioner

- BUILD_OS_IMAGE.md
- test-manager/src/tests/mod.rs
- test-manager/src/tests/tunnel.rs
- test-rpc/src/client.rs
- test-rpc/src/lib.rs
- test-rpc/src/meta.rs
- test-runner/src/main.rs
Add a couple of tests:
1. Fail if the app fails to connect. On Linux, also sanity check whether the wireguard tunnel has a PSK set with `wg show wg-mullvad`.
2. Check if PQ works when multihop and udp-over-tcp are both enabled.
Other changes: Linux images must include `wireguard-tools` now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/65)
> Add tests for quantum-resistant tunnels and multihop

- test-manager/src/run_tests.rs
- test-manager/src/tests/account.rs
- test-manager/src/tests/install.rs
- test-manager/src/tests/test_metadata.rs
- test-manager/test_macro/src/lib.rs
Tests can now be specified as always_run tests which will always run regardless of what filters are provided to the test framework. Test can also be specified as needing to succeed which means the test framework will stop running if the test fails.
Both of these default to false which means that filtering is practical and normal tests will run properly after installation and login has been done. It also means that if some test is temporarily failing due to external circumstances (such as some network service being down) will not cause the entire run to halt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/67)
> Add test attributes always_run and must_succeed-des-123

- Cargo.lock
- docs/REMOTE_MANAGEMENT.md
- test-manager/Cargo.toml
- test-manager/src/config.rs
- test-manager/src/container.rs
- test-manager/src/main.rs
- test-manager/src/vm/qemu.rs
- test-manager/src/vm/tart.rs
See `REMOTE_MANAGEMENT.md` for an explanation of how to use this. One limitation is that it is a bit flaky with tart right now, since we don't control the assigned port there. But I still haven't disabled the flag on macOS.
Completes DES-160.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/70)
> Add VNC support to test manager (Linux/Windows)

- BUILD_OS_IMAGE.md
It seems like tasks by default are stopped if they run for too long. This PR just adds some more notes to the `BUILD_OS_IMAGE.md` for how to set up the scheduled task properly.
Fixes DES-146.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/71)
> Add more notes about scheduled runner task on Windows

- test-manager/src/mullvad_daemon.rs
- test-manager/src/run_tests.rs
- test-manager/src/tests/mod.rs
- test-manager/src/tests/test_metadata.rs
- test-manager/test_macro/src/lib.rs
- test-rpc/src/mullvad_daemon.rs
When we stopped treating all tests as `must_succeed`, the cleanup code was never updated. Fix by always running the cleanup code when a test fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/72)
> Reset daemon state after failing tests

- Cargo.lock
- ci-runtests.sh
- test-manager/Cargo.toml
- test-manager/src/tests/install.rs
Rather than set an explicit commit hash, clear the cache. We need to do the latter because (1) it keeps growing indefinitely, and (2) cargo uses the cached version rather than the most recent commit on the branch.
Fixes DES-177.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/75)
> Clear cargo cache in CI script

- Cargo.lock
- test-manager/Cargo.toml
- test-manager/src/logging.rs
- test-manager/src/main.rs
- test-manager/src/mullvad_daemon.rs
- test-manager/src/run_tests.rs
- test-manager/src/tests/account.rs
- test-manager/src/tests/install.rs
- test-manager/src/tests/mod.rs
- test-manager/src/tests/settings.rs
- test-manager/src/tests/test_metadata.rs
- test-manager/src/tests/tunnel.rs
- test-rpc/src/client.rs
- test-rpc/src/lib.rs
- test-runner/src/main.rs
- test-runner/src/sys.rs
Add a `--verbose` option to `run-tests`. By default, this is disabled and log output is suppressed for successful tests.
Fixes DES-196.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/76)
> Hide successful test logs by default

- test-manager/src/main.rs
- test-manager/src/vm/mod.rs
- test-manager/src/vm/provision.rs
- test-manager/src/vm/ssh.rs
- test-manager/src/vm/update.rs
In VM images where there are known package managers (e.g. `apt` in Ubuntu/Debian, `dnf` in Fedora) we could allow for automatically updating system packages before proceeding with running tests.
This PR adds the `--update` flag to the `test-manager` CLI. If the flag is set, the VM's package manager is invoked with an update/upgrade request.
Note that these updates are not persisted in the VM image as of yet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/85)
> Update vms before running tests (if possible)

- Cargo.lock
- test-rpc/src/lib.rs
- test-runner/Cargo.toml
- test-runner/src/main.rs
- test-runner/src/sys.rs
The app resource directory is not necessarily in `PATH` when the test runner starts, since it isn't initially installed. This causes some UI tests to fail.
This PR works around this problem by always running `exec` with an updated `PATH` var.
Currently, this is only done on Windows, because we don't need to make any changes to `PATH` on other OSes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/92)
> Update PATH before running UI tests

- test-manager/src/tests/helpers.rs
- test-manager/src/tests/settings.rs
- test-manager/src/tests/tunnel.rs
- test-manager/src/tests/tunnel_state.rs
As part of our automated tests, we want to assure that the internet is reachable through the VPN tunnel. To verify connectivity, we can request internet resources which are not the currently connected relay. Also, try something more elaborate than a ping (i.e. check for HTTP `200` from `am.i.mullvad.net`).
This is prone to network failures, which is why we retry each request 3 times before we consider it a failure.
Use the strategy in actual tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/87)
> Implement a generic connection check strategy

- Cargo.lock
- ci-runtests-and-report.sh
- ci-runtests.sh
- scripts/ssh-setup.sh
- test-manager/src/tests/tunnel.rs
- test-runner/Cargo.toml
- test-runner/src/sys.rs
This makes the CI script usable on macOS. It also fixes two issues: (1) The API override config did not persist across reboots in the guest, and (2) the test runner did not have `/usr/local/bin` in its path, causing `mullvad` not to be found by the GUI tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/96)
> Fix various macOS issues

- ci-runtests.sh
Previously, the array of OSes would be interpreted as a string, which would make the `os` argument of the `download_e2e_executable` function be equal to the string of all `TEST_OSES`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/99)
> Actually create array of OSes in CI script

- test-manager/src/tests/helpers.rs
- test-manager/src/tests/tunnel.rs
- test-manager/src/tests/tunnel_state.rs
- test-manager/src/tests/ui.rs
Fix long-standing `TODO` comment in test case `test_connected_state`. The relay used in the test is no longer hard coded, which makes the test more robust to changes in the testing environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/100)
> Refactor/generalize relay selection in `test_connected_state`

- ci-runtests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/103)
> Fix missing default value for `$TEST_OSES` in `ci-runtests.sh`

- test-manager/src/config.rs
- test-manager/src/main.rs
- test-manager/src/summary.rs
- test-manager/src/tests/tunnel_state.rs
- test-manager/src/vm/mod.rs
- test-manager/src/vm/network/linux.rs
- test-manager/src/vm/network/mod.rs
- test-runner/src/net.rs
- test-runner/src/package.rs
This small PR just cleans up the remaining `clippy` warnings in the repository.
As the PR is based on #91 it is preferably rebased on top of main after that one is merged. It would also be nice to squash all of these commits into one commit before merge :nerd_face:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/93)
> Clean up remaining `clippy` warnings

- README.md
- test-runner/src/package.rs
- test-runner/src/sys.rs
I accidentally broke `test-runner` builds for Windows in #93, so this PR fixes that while cleaning up the remaining `clippy` complaints (for Windows specifically) :crossed_fingers: 
I went ahead and added a section in the `README`  about building the `test-runner` for different platforms. I totally blanked on Windows being a target in the first place, so hopefully this will serve as a reminder on what to test before trying to merge conditional compilation stuff :sweat_smile:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/104)
> Fix `test-runner` Windows build

- test-manager/src/tests/dns.rs
- test-manager/src/tests/helpers.rs
- test-manager/src/tests/install.rs
- test-manager/src/tests/tunnel.rs
- test-rpc/src/client.rs
- test-rpc/src/lib.rs
- test-runner/src/main.rs
A couple of small changes:
* `test_content_blockers` fails once in a blue moon. Likely because `set_dns_options` isn't guaranteed to take effect *immediately*.
* `test_install_new_app` fails once in a blue moon. Sleep for a while after restarting the daemon. The UDS isn't necessarily immediately available as soon as the service is running.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app-tests/105)
> Fix nonrobust tests
